# Project: Project1
# Makefile created by Dev-C++ 5.5.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/Program Files/Dev-cpp/MinGW32/lib" -L"C:/Program Files/Dev-cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -mwindows -g3
INCS     = -I"C:/Program Files/Dev-cpp/MinGW32/include"
CXXINCS  = -I"C:/Program Files/Dev-cpp/MinGW32/include" -I"C:/Program Files/Dev-cpp/MinGW32/lib/gcc/mingw32/4.7.2/include/c++"
BIN      = NI_Test.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
